name: Build
on:
    push:
        branches:
            - master
            - develop
jobs:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout GitHub Action repository
          uses: actions/checkout@v2

        - name: Install NodeJS version 20
          uses: actions/setup-node@v2
          with:
              node-version: 20

        - name: Cache Dependencies
          uses: actions/cache@v2
            with:
              path: '**/node_modules'
              key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

        - name: Install Dependecies
          run: yarn install

        - name: Build Project
          run: yarn run build
