name: Test
on:
  push:
    branches:
      - master

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Using NodeJS16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependecies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Execute Code
        uses: ./